### ISSUE TITLE
Inconsistent behavior with inline script tags and popstate

### ISSUE THREAD

**Issue by chanind** [defunkt/jquery-pjax#241]
I use inline script tags on my pages to pass data to javascript. For example:

``` html
<script type="text/javascript>
new Page({userId: 17, pageName: "blah", ... });
</script>
```

When using pjax, this works clicking through the site normally. However, when the back/forward button is pressed, the script doesn't seem to execute 90% of the time (randomly it does run sometimes, which is confusing). I can see the script tag getting placed in the page content, and when I put a breakpoint on the spot in pjax where the `container.html(contents)` line is run, which inserts the popped snippet, I can see the script tag in there too. Strangely, if I manually run container.html(contents) at that break point, the first time I run it the content is swapped and the script tag is not executed. However, if i run it a second time the script tag is evaluated and run.

This doesn't make any sense to me because when just clicking around through the site pjax internally just uses `context.html(contents)` to insert the loaded content, same as it does when using popstate, but the script tags always get executed when just clicking around. Is this a bug with pjax or jquery or is there something obvious I'm overlooking? This same behavior occurs on Chrome and Firefox. I assume this might be related to https://github.com/defunkt/jquery-pjax/issues/48 except that scripts are being run, just inconsistently on popstate. Using jQuery 1.9

**Comment by MrOrz** [comment]
@chanind I bumped into a wierd situation that my inline scripts were executed twice during popstate.

It turns out that on popstate, the page contents *may* have been fetched via ajax. This happens after a manual refresh or a pjax timeout, which refreshes the page and clears the pjax state cache. Whenever the page contents are fetched by ajax, pjax would executes inline scripts by itself, even during popstate.

I managed to handle the situation by extending @chanind 's snippet a bit. This should prevent the inline scripts from being executed twice:
```js
$(document).on('pjax:popstate', function() {
    var isContentFromCache = true;
    $(document).one('pjax:complete.popstate-handling', function(){
        // Content loaded from ajax
        isContentFromCache = false;
    });

    $(document).one('pjax:end', function(event) {
        if(!isContentFromCache){
            // Inline scripts already executed by pjax.
            return;
        }else {
            $(event.target).find('script').each(function() {
                $.globalEval(this.text || this.textContent || this.innerHTML || '');
            });
            $(document).off('.popstate-handling'); // Cleanup the callback that's not fired
        }
    });
});
```

After all this, I think I should have avoided inline scripts from the beginning :P
