### ISSUE TITLE
The URL should update if the request hits a 301/302 redirect.

### ISSUE THREAD

**Issue by bsthomsen** [defunkt/jquery-pjax#426]

**Comment by staabm** [comment]
> What use case do you have in mind?

We experince the same problem in a app right now. The use case is:

User clicks a "+" button to create a vehicle. while vehicle creation we don't show all possible options to the user because for some we the a vehicle-id first. This is the reason why after validation + submit we redirect the user to the detail-view again which brings up all available features for this car.

Form submit is handled using pjax, therefore we need the redirect functionality their. will try the `X-PJAX-URL` way now.

**Comment by bsthomsen** [comment]
Well the concrete problem for me is for example, we have a list of devices:
Appe Iphone 5s
Samsung Galaxy S5

While the Samsung Galaxy S5 should go straight to /device-name/ the Apple Iphone 5s might have operating systems, so therefore if the Apple iPhone 5s have operatingsystems it will redirect 301 to a url /device-name/select-os/.

Of course this could be solved by printing the correct links in the first place, but there could be other use cases where some content has been permanently moved. Then it would only make sense that the url updated because the content shown is actually not the content corresponding to the url.

I get that this problem might not be pjax's to solve but I personally think you should consider it. Becuase people use this plugin because it's the perfect tool for a backend developer. And they just want their backend reflected in the frontend with a neet little 5-10 line jquery plugin like this.

**Comment by mislav** [comment]
I'm not sure that we're all on the same page here, but just to reiterate what the general problem with ajax and redirects is:

1. ajax requests `/foo` URL
2. server processes `/foo` and 30x-redirects to `/bar`
3. ajax automatically follows redirects, receives HTML response for `/bar`
4. from ajax response, it's impossible to detect that a 30x redirect happened or what was the final URL

Since pjax is implemented using ajax, we are left with this same problem with redirects. The only solution we can propose right now, and this is suggested in the README, is that the server sets `X-PJAX-URL` response header so that this value gets read by pjax and updates the URL accordingly. So, when you do a redirect, have the final endpoint send the HTML response as well as the current URL as `X-PJAX-URL` header and you should be fine.

Any other questions?

**Comment by ivan-matthews** [comment]
(Download this cookie plugin for jQuery. This is not an advertisement.
 https://github.com/carhartl/jquery-cookie/blob/master/src/jquery.cookie.js )
### JS:
```
	$(document).on('pjax:end', function(event, xhr, options){
		Redirect();
	});

	function Redirect(){
		let redirect = $.cookie('redirect');
		if(redirect !== location.pathname){
			history.pushState(null, null, redirect);
			$.cookie('redirect',null,{expires:-99999})
		}
	}
```
### PHP:

```
$link_to_redirect = '/link/to/redirect';
setcookie('redirect', $link_to_redirect, 0, '/', null, false, false);
header("Location: {$link_to_redirect}");
```

**Comment by ivan-matthews** [comment]
Add to your template file in #pjax-container block 
```
<div class="hide" style="display:none" id="current-url"><?php print $_SERVER['REQUEST_URI'] ?></div>
```
and jQuery:
```

$(document).on('pjax:end', function(event, xhr, options){
	let current_url = $('#current-url').text();
	if(current_url !== location.pathname){
		history.pushState(null, null, current_url);
	}
});

```
