### ISSUE TITLE
SyntaxError: Unexpected identifier 'cachePop'

### ISSUE THREAD

**Issue by thelucid** [defunkt/jquery-pjax#471]
On line `450` there is the aforementioned error. I am using uglify to compress the javascript so maybe it's where there are a lack of semicolons at line ends?

**Comment by mislav** [comment]
No, sorry, but [our CI passes](https://travis-ci.org/defunkt/jquery-pjax/builds/42826759) for the latest release and we use the library on GitHub.com, meaning that there are no syntax errors in the code itself. If you ran pjax source code through a tool and it produced invalid JavaScript, then your tool might be broken or you should try different parameters for the uglifier.

**Comment by thelucid** [comment]
@mislav Do you mind me asking what minifier you are using as it errors for me? Uglify is pretty common.

**Comment by mislav** [comment]
For Zepto.js (another semicolon-less project that I help maintain) we use uglify-js 2.4 and it produces valid minified JS because it rewrites expressions and inserts semicolons when removing newlines. In GitHub.com we use uglifier 2.5, which wraps UglifyJS of presumedly the same version. I think we use all the [default options](https://github.com/lautis/uglifier#usage)

**Comment by thelucid** [comment]
@mislav Great, will have to investigate rather as I'm using the default options also.

**Comment by mislav** [comment]
Let us know how it goes.
