### ISSUE TITLE
NPM package.json add

### ISSUE THREAD

**Issue by cypherq** [defunkt/jquery-pjax#492]
Can we add NPM package.json, so it will be possible to pull `jquery-pjax` as NPM dependency?

**Related sources:**
http://blog.npmjs.org/post/111385956875/welcome-jquery-developers
http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging
http://blog.npmjs.org/post/111475741445/publishing-your-jquery-plugin-to-npm-the-quick

http://blog.kewah.com/2014/npm-as-a-front-end-package-manager/

**Comment by mislav** [comment]
Thanks for the suggestion, but [I'm not interested in maintaining](https://twitter.com/mislav/statuses/560587920709398529) NPM support right now, especially because I personally don't use nor condone NPM for client-side JS.

Right now I'm the only person who maintains jquery-pjax, so I guess the decision ends there.

**Comment by lencioni** [comment]
npm 3 (which is currently in beta) [aims at solving some of the issues at using npm for client-side JS](http://blog.npmjs.org/post/122450408965/npm-weekly-20-npm-3-is-here-ish). Once that is out, would you reconsider supporting it?

**Comment by mislav** [comment]
@lencioni Sure; once npm front-end support is out of beta and works well and developers love it, give me a ping here.

**Comment by hacdias** [comment]
@lencioni a temporary solution maybe using [napa](https://github.com/shama/napa). I hope it helps.
