### ISSUE TITLE
PJAX Best practices

### ISSUE THREAD

**Issue by proov** [defunkt/jquery-pjax#508]
Hello,

i tried several times to create a clean and functional app.js for my website but i think i'm doing wrong.. Here is what i want to do:

- Pjax on all my website (menu links, logo link, portfolio links etc.)
- Elements Animations/Transitions on page load (both dom ready load and pjax:end)
- Elements Animations/Transitions on some elements links (pjax fire on animations/transition end)
- Special Animations/Transitions on some pages

I am using velocity.js to manage animations/transitions effects but maybe it's a bad idea. I can do this by adding a class on body and doing this in pure CSS

i tried to create my main app.js like this

```javascript
(function($){
/**
 * VARS
 **/
$pjax_container = $("#main"); // And some other vars


/**
 * FUNCTIONS
 **/
function isotopeInit(){ //... }
function homeCarousel(){ //... }

/**
 * PJAX
 **/
$(document).pjax("a.pjax", "#main");
$(document).on("pjax:start", function(){ //... }
$(document).on("pjax:end", function(){
    isotopeInit(){ //... }
    if (body.hasClass("home"){
        homeCarousel(){ //... }
    }
   
} 

/**
 * DOM Ready
 **/
isotopeInit(){ //... }
if (body.hasClass("home"){
    homeCarousel(){ //... }
}

})(jQuery);
```

But it wont cover all i want, sometimes i have some strange things... i think i'm doing the wrong way.. How do you handle all the events and animations ?

Many thanks :)

**Comment by mislav** [comment]
Hi, unfortunately we don't yet support pjax operations being subject to arbitrary delays due to animations. See #498 for more discussion.

It's possible to create *some* animations, but eventually trying to animate transitions between pages will be more trouble than it's worth. This will only be possible after we fundamentally rewrite pjax using Promises to allow customization by delaying certain aspects of it.
