### ISSUE TITLE
Button values not submitted in Firefox

### ISSUE THREAD

**Issue by tdhooper** [defunkt/jquery-pjax#513]
See the following example:
http://jsfiddle.net/tdhooper/cxcv2rnb/3/

The 'language' value is not included in the post data.

This works in Chrome, or in Firefox when pjax is disabled.

**Comment by mislav** [comment]
Thanks for reporting. This is a known problem; please follow https://github.com/defunkt/jquery-pjax/pull/390#issuecomment-42797352 for updates.

BTW, your fiddle to demonstrate this doesn't actually use PJAX because it's a cross-domain post. But yes, on a single site this would definitely be a problem.

For now you could solve this by observing clicks to submit button elements and adding their name/value pairs as hidden `<input>`s to the form.

**Comment by tdhooper** [comment]
Thanks for the update.

**Comment by Shade-** [comment]
Temporarily solved with:

```javascript
	$(document).on('click.thunderboard', 'form input[type="submit"]', function(e) {
		$(this).closest('form').append($(this).clone().attr('type', 'hidden'));
	});
```

But I believe there should be a built-in solution for this.
