### ISSUE TITLE
Pjax breaks popstate cached content after page refresh

### ISSUE THREAD

**Issue by trompx** [defunkt/jquery-pjax#522]
Hello everyone,

First let me explain how my pages load and how this problem occurs.
On each page, I have a "pjax-container" in which I load som content with pjax.
After the content has been loaded, new content is loaded with ajax inside a div inside "pjax-container" (infinite scroll wall). Now if I :
- navigate to page 1, scroll and load some content
- navigate to page 2, then click on the back button
  The cache of page 1 is loaded with all the ajax content.

However, if before clicking the back button I reload page 2, only the initially loaded content in "pjax-container" is loaded without the content loaded with ajax requests. (I checked the event.target.outerHTML content on pjax:end too and it is really not there).

If I load 10 pages before reloading, all the 10 pages have the ajax content missing. What may cause the ajax content to disappear on all history states when I refresh the page while still preserving the initial data loaded in "pjax-container" ?

Other question : when I refresh the page, the forward history is not cleared, is there an easy way to iterate over all the forward states and remove them ?

Thank you in advance for your help

**Comment by mislav** [comment]
> However, if before clicking the back button I reload page 2, only the initially loaded content in "pjax-container" is loaded without the content loaded with ajax requests.

Unfortunately, this is expected. Pjax keeps cached HTML for previous pages in JS memory, in order to use them after a popstate event. The extra content loaded through inifinite scrolling would get cached as well. However, after page 2 refresh, the in-memory cache is gone, and on popstate pjax will simply request the URL of the previous page from the server. The response will only contain the contents of the first page, without any content that might have been additionally loaded by scrolling.

I'm sorry, but there's nothing pjax can do here. You should assume that your users won't have to refresh the site manually. And if they do, and lose some pages loaded with inifinite scroll when going back, it shouldn't be a huge deal. (It does suck; I know.)

**Comment by trompx** [comment]
Thank you very much for the fast answer, I really appreciate. Good to know the cause of the problem, I thought I was doing something bad.

Reading your post, I immediatly tried to implement sessionStorage to handle this. However I quickly hit a wall getting the following error "TypeError: Converting circular structure to JSON".
In fact it is "not" possible to stringify circular Dom elements with just JSON.stringify. Workarounds exist but I encoutered errors so gave up at this time.

For those interested, here are some links to investigate possible solutions :
- https://github.com/douglascrockford/JSON-js/tree/ad6079cbd8dc362a3cc42e1f97c01aa5ccd48bfe : some users managed to make it works with douglas crockford cycle.js but I got errors
- http://stackoverflow.com/questions/11616630/json-stringify-avoid-typeerror-converting-circular-structure-to-json : other solutions I did not try (maybe in the future)
- http://stackoverflow.com/questions/9382167/serializing-object-that-contains-cyclic-object-value : some more solutions 

However I don't know if it is a good idea to store that in sessionStorage and may not be good performance wise.

What I ended up doing for the time being is to load again the ajax content if the page is not cached anymore.

Thanks again.
