### ISSUE TITLE
PJAX and Chosen plugin

### ISSUE THREAD

**Issue by craigphiz** [defunkt/jquery-pjax#526]
I'm seeing an issue with the [chosen plugin](http://harvesthq.github.io/chosen). The plugin works well on full page load and pjax loaded but fails to respond when the (dreaded!) browser back button is used.

I tried this [fork](http://hackersome.com/p/clipperhouse/jquery-pjax) and it fixed the issue with chosen but caused issues with a lightbox plugin.

Is any one else seeing this? Have a workaround/fix? Any help gratefully received!

**Comment by staabm** [comment]
could you post a jsfiddle which reproduces the issue. we use chosen with pjax and did not run into problems as of today.

**Comment by mislav** [comment]
The common problem with pjax is usually:

1. On DOM load of the initial page, you invoke a plugin. In this case, something like: `$(".chosen-select").chosen()`
2. The plugin rewrites the DOM and sets up event handlers.
3. Somebody clicks a link. The page transition is handled by pjax. Previous DOM state is cached in memory.
4. Somebody uses Back button. Previous DOM state is restored (the one that includes the result of what a plugin might have done), but not the event handlers. Therefore, you might end up with something that *looks* like a Chosen-enhanced select box, but for some reason it isn't interactive.

This is all based on guesses. Please provide some sample code if possible. I understand it's hard to use jsfiddle for this because the only way to test pjax is to have page transitions.

**Comment by craigphiz** [comment]
Thanks to you both. Yes @mislav, I also guess the behaviour is due to as you describe. 

I've noticed some plugins behave better with pjax and the back button. I imagine it's because they use .on() ?   I'm seeing the same issue (event handlers?) with [magnific popup](http://dimsemenov.com/plugins/magnific-popup) also. 

Would it help if I posted a link to a test site or would you need more interaction with the code? I don't know how to use jsfiddle, jsbin... to create a demo for this.

Many thanks!

**Comment by craigphiz** [comment]
**Update**: Chosen is now working fully with pjax after upgrading to chosen v1.4.2. I hope this helps someone.

**Comment by mislav** [comment]
Thanks for letting us know!

**Comment by volnei** [comment]
@craigphiz some hack? It's not working for me when back or forward buttons.

**Comment by craigphiz** [comment]
@volnei Hi, yes it's working well. I have this in a custom.js file to initialize chosen on each page load, whether a full load, with pjax or back/forward buttons ('popstate'):

```
$(document).on('ready pjax:popstate pjax:end', function() {
		if ($('#chzn').length > 0){
			$('#chzn').remove();
		}
		$('#chzn').chosen({
			search_contains: true,
			disable_search_threshold: 10,
		});	
});
```

Good luck!

**Comment by volnei** [comment]
Thank you @craigphiz :smile:

**Comment by craigphiz** [comment]
Hi @volnei , you're welcome :) 

It might help others if you mention here that the suggestion I gave worked for you, or otherwise.

**Comment by azanelli** [comment]
I'm having the same problem with [select2](https://select2.github.io/) and [icheck](http://icheck.fronteed.com/) plugins. Is there some news about this issue? is there a way to solve this in general, for other plugins other than chosen?

I think the problem is exactly described by @mislav. Both select2 and icheck modify the DOM then attach some event handlers. When the page is loaded with the back/forward buttons the browser shows the modified DOM but event handlers doesn't works. If I try to reinitialize the plugin (on `pjax:end`) it happen that it does some mess re-modifying the DOM. Any solution/suggestions/workaround?

**Comment by jk2K** [comment]
@azanelli , for [select2](https://select2.org/), I have a workaround

```js
$(document).on('pjax:end', function (event) {
    $(event.target).find('.select').removeClass('select2-hidden-accessible');
    $(event.target).find('.select2').remove();
    $('#p0 .select').select2();
});
```
select2 will do two things after initialization

![image](https://user-images.githubusercontent.com/4025839/37270563-3db602b8-260a-11e8-9530-6739d7c71c63.png)

1. add `select2-hidden-accessible` css class to your jquery selector, here is `$(.select')`

2. generate a span tag with `select2` css class next to the select tag

the [destroy](https://select2.org/programmatic-control/methods#destroying-the-select2-control) method of select2 not work for pjax cached container, it will throw error `The select2('destroy') method was called on an element that is not using Select2.`

we need to manually remove the Select2 widget from the target element, and reinitialize

**Comment by RichardTMiles** [comment]
Another solution is to create a one time event listener that will be fired betweeen requests. I created a gist to show how you may get more control of the state of plugins. It is essentially all that is happening when pjax fires its plugins 

[https://gist.github.com/RichardTMiles/851ed048b7939e7c01942a12ebe27445](url)
