### ISSUE TITLE
dataType: "script" question

### ISSUE THREAD

**Issue by leighmackay** [defunkt/jquery-pjax#532]
Hello,

Why should we not use dataType "script" with Pjax?

Noticed it still replaced the contents of container.

Thank you.

**Comment by mislav** [comment]
`dataType: "script"` means you're requesting to get `application/javascript` response from the server which is then eval'd as a script. Pjax expects to get HTML response from the server which it then injects as the new contents of a pjax container element.

So the answer is: you should not use `dataType: script` because then the server most likely wouldn't return HTML content which pjax needs.

**Comment by leighmackay** [comment]
@mislav ended up using ``` dataType: script  ``` then returning pjax in the eval'd response, it's awesome. 

I'm a huge fan of Zepto and your work, wish you would write a book :D

$.pjax({ url: "/magic_carpet", container: "#bottle" });
// any other js for response
