### ISSUE TITLE
Pjax infinite loop problem

### ISSUE THREAD

**Issue by MetSystem** [defunkt/jquery-pjax#541]
Why $. Pjax ({url: " main.htm ", container: '# home'}) write directly in $(function () {} it can cause has been  main.htm. On both sides of the HTM circulation load switch
Use Google browser

**Comment by mislav** [comment]
You never explained what you're trying to do, but the reason why you have an infinite loop problem is because you're performing `$.pjax()` call on every page load. Pjax results in a page load, meaning that every page load will trigger another page load, resulting in infinite loop.

Don't perform `$.pjax()` within `$(function() {})`.

**Comment by MetSystem** [comment]
That is what I use.
$(function() {
  $.pjax();
}).
Other people to download version of history customer normal use
While downloading on making a cyclic loading.

**Comment by MetSystem** [comment]
Try again today, found that didn't seem that cycle of problem.
It's odd.
