### ISSUE TITLE
Apply functions after load to new content

### ISSUE THREAD

**Issue by TheZoker** [defunkt/jquery-pjax#568]
Hi there,

I use this script and its awesome!
But I have a problem: After document ready some functions are called on my content. When I load it via this script, these functions are not called on the new content.

Can somebody help me doing this?

Also it would be nice, if somebody could tell me, how to trigger pace, when new content loads:
http://github.hubspot.com/pace/

Regards,
Zoker

**Comment by jslirola** [comment]
I have the same problem. Any help?

**Comment by ApfelUser** [comment]
In general you just have to do:

```javascript
$(document).on('pjax:end',   function() {
    //functions to be executed
});
```

For you @TheZoker that'd be:

```javascript
$(document).on('pjax:start', function() {
    Pace.start();
});
$(document).on('pjax:end', function() {
    Pace.stop();
});
```

I am not sure whether the above is a 100% correct, because Pace seems to be a "automatic" progress bar - so it normally detects ajax requests by itself. For this reason I'd recommend **[NProgress](https://github.com/rstacruz/nprogress)** for your task. In that case it'd be:

```javascript
$(document).on('pjax:start', function() {
    NProgress.start();
});
$(document).on('pjax:end', function() {
    NProgress.done();
});
```

Hope that helps
