### ISSUE TITLE
Pjax duplicates js events

### ISSUE THREAD

**Issue by roundge** [defunkt/jquery-pjax#570]
Hi there, 

I use PJAX for the navigation into my application, wich have many scripts, and many events.
But after replacing content, pjax eval() script tags, and events are duplicated. 

For exemple : 
```
$('document').on('click', 'a#toggle-menu', function(){
      $('#menu').toggle();
});
```
This event is present in all pages.
After the first load, click event run correctly, but on the second call, the event is duplicated.. and many calls => many duplication..
So, I can load this script just on the first load. OK.

But, with jquery ui widget ? On the first loading, ok, but second the widget doesn't exist.

I've tried to "kill" events before show the new page 
Exemple : 
```
$(document)
      .on('pjax:start', function() {
        $('#content, #content *').off();
      });
``` 
But this is really inconsistent/irregular/bad...

My questions are
- How to be sure that scripts are really eval() after the DOM ready event ? ( already tried pjax:success event ) 
- How to have unique events after scripts reload ? (no more events duplication)

Wrapping all javascript into `$(document).on('ready pjax:success ', function(){....});`  doesn't resolve the duplicate issue.

*Sorry for my bad english i'm french, I hope you'll understand me*

**Comment by bastianh** [comment]
Using javascript in the block that gets replaced by pjax is problematic.

if you do `$('document').on(...)` you attach an event handler to the root document of the page. pjax don't know that and don't change the document when you navigate, so this event handler never gets removed. With every navigation you add more and more event handlers to the document.

instead of adding an event handler to the document you could try to use bind (http://api.jquery.com/bind/) to attach the clicks directly to the elements... so they are also removed when the elements are removed.

you also could try to use .live (http://api.jquery.com/live/) to set up the function for now and all coming pages .. but this should be outside of the pjax element to make sure it is only called once for the page during setup... possibly in a ready block.

**Comment by roundge** [comment]
Thanks @bastianh, I see, I will attach event on another DOM level. I close this issue. Thanks!
