### ISSUE TITLE
Redirect to another page after submit without reload?

### ISSUE THREAD

**Issue by huonsokly** [defunkt/jquery-pjax#663]

**Comment by fari-99** [comment]
have the same problem, after submit, I need to redirect to another page, the pjax is working, the page not reloads after submit, but when come to another page it reloads the page. if I remember correctly there is a way to make URL in pjax change on the server side, so I use it and maybe because I do not understand how to use it, and the page still reloads.

**Comment by fari-99** [comment]
#629

**Comment by mislav** [comment]
Sorry, there is not enough information given here for us to be able to provide any advice. It sounds like this might be a problem with usage of this project, and not a bug in our code. If you do think this is a bug, please reopen this and provide more information, such as steps to reproduce. Thank you!
