### ISSUE TITLE
Form submit handler works only before first PJAX request - only once

### ISSUE THREAD

**Issue by iliaross** [defunkt/jquery-pjax#678]
Hi,

Thanks for amazing plugin.

Could you tell me, which direction to look, if you can reproduce it and why when, I hit any link that is processed by PJAX, then even handler for submit stops working?

I have this code:

```JavaScript
$(document).on('submit', 'form', function(event) {
    console.log( 'Allowing PJAX forms ..', event );

    $.pjax.submit(event, '[data-dcontainer]', {
      timeout: 3000,
      type: "POST",
      fragment: "[data-container]"
    })
  })

```

If I hard reload the page and hit some form element on the page, then the code works fine - the data is submitted and proper results returned and content replaced. But if I do it the second time - nothing works, meaning `$(document).on('submit', 'form', function(event) .. ` doesn't fire again.

What could cause that? Is there a way to unbind the event and run it again for new content on `ready pjax:end`? I don't know yet what would be the solution?

**Comment by iliaross** [comment]
This issue was cause by the invalid HTML generated by the server.

Sorry for disturbance.

**Comment by anandiamy** [comment]
Hi @rostovtsev 

I have the same problem ...
Please tell me how do you solve this problem?

**Comment by iliaross** [comment]
I don't remember exactly what was the issue but most issues are caused by unparseable/invalid HTML, like missing opening/closing body tag or other.

**Comment by dnnnvx** [comment]
I'm a bit late, but the problem is that the form is inside the pjax container, so it's dynamically generated at every request, so the first pjax request will replace the form tag which can't be reached by jQuery. To solve this problem, bind the event outside of the pjax container:

Use: $(document).on('beforeSubmit', '#my-form', function(e) { /*something*/ });

Instead of: $('#my-form').on('beforeSubmit', function(e) { /*something*/ });
